version: '3.1'

services:

  db:
    image: "postgres:alpine"
    env_file: 
      - postgres.env
    container_name: "my_postgres"
    ports:
      - 5432:5432
    env_file:
      - postgres.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down  
volumes:
  database-data: # named volumes can be managed easier using docker-compose
  