version: '3.1'

services:

  db:
    image: "postgres:12.4"
    env_file: 
      - postgres.env
    container_name: "my_postgres"
    ports:
      - 5432:5432
    hostname: mypostgres      
    env_file:
      - postgres.env # configure postgres
    networks: 
      - my_network

 

volumes:
  database-data: # named volumes can be managed easier using docker-compose
  
networks:
  my_network:
    driver: bridge  
