// Code generated by MockGen. DO NOT EDIT.
// Source: ../user/all.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	entity "github.com/faceit/test/entity"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// Mockall is a mock of all interface
type Mockall struct {
	ctrl     *gomock.Controller
	recorder *MockallMockRecorder
}

// MockallMockRecorder is the mock recorder for Mockall
type MockallMockRecorder struct {
	mock *Mockall
}

// NewMockall creates a new mock instance
func NewMockall(ctrl *gomock.Controller) *Mockall {
	mock := &Mockall{ctrl: ctrl}
	mock.recorder = &MockallMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Mockall) EXPECT() *MockallMockRecorder {
	return m.recorder
}

// All mocks base method
func (m *Mockall) All(ctx context.Context, filter, title string) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx, filter, title)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All
func (mr *MockallMockRecorder) All(ctx, filter, title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*Mockall)(nil).All), ctx, filter, title)
}
